import assert from 'node:assert/strict'
import { test } from 'node:test'
import {
  HEART_MODE_REFILL_COUNT,
  HEART_MODE_REFILL_THRESHOLD,
  LYRICS_RETRY_DELAYS_MS,
  NATIVE_PAUSE_CONFIRMATION_MS,
  NATIVE_PLAYBACK_INFO_INTENT_GRACE_MS,
  NATIVE_PLAYBACK_INFO_POST_CONFIRMATION_GRACE_MS,
  NATIVE_PLAYBACK_INFO_REFRESH_DELAY_MS,
  PLAYBACK_TOGGLE_INTENT_GRACE_MS,
  RENDERER_PLAYBACK_WATCHDOG_MS,
  START_FILE_PLAYBACK_INFO_REFRESH_ATTEMPTS,
  START_FILE_PLAYBACK_INFO_REFRESH_DELAY_MS
} from './playerConstants.ts'

test('player playback constants retain their exact values', () => {
  assert.deepEqual([...LYRICS_RETRY_DELAYS_MS], [750, 2000, 5000])
  assert.equal(HEART_MODE_REFILL_THRESHOLD, 3)
  assert.equal(HEART_MODE_REFILL_COUNT, 20)
  assert.equal(RENDERER_PLAYBACK_WATCHDOG_MS, 220)
  assert.equal(PLAYBACK_TOGGLE_INTENT_GRACE_MS, 1200)
  assert.equal(NATIVE_PLAYBACK_INFO_INTENT_GRACE_MS, 2500)
  assert.equal(NATIVE_PLAYBACK_INFO_POST_CONFIRMATION_GRACE_MS, 500)
  assert.equal(NATIVE_PLAYBACK_INFO_REFRESH_DELAY_MS, 80)
  assert.equal(START_FILE_PLAYBACK_INFO_REFRESH_ATTEMPTS, 4)
  assert.equal(START_FILE_PLAYBACK_INFO_REFRESH_DELAY_MS, 120)
  assert.equal(NATIVE_PAUSE_CONFIRMATION_MS, 500)
})
