export const LYRICS_RETRY_DELAYS_MS = [750, 2_000, 5_000] as const

export const HEART_MODE_REFILL_THRESHOLD = 3
export const HEART_MODE_REFILL_COUNT = 20
export const RENDERER_PLAYBACK_WATCHDOG_MS = 220
export const PLAYBACK_TOGGLE_INTENT_GRACE_MS = 1200
export const NATIVE_PLAYBACK_INFO_INTENT_GRACE_MS = 2500
export const NATIVE_PLAYBACK_INFO_POST_CONFIRMATION_GRACE_MS = 500
export const NATIVE_PLAYBACK_INFO_REFRESH_DELAY_MS = 80
export const START_FILE_PLAYBACK_INFO_REFRESH_ATTEMPTS = 4
export const START_FILE_PLAYBACK_INFO_REFRESH_DELAY_MS = 120
export const NATIVE_PAUSE_CONFIRMATION_MS = 500
