import { lightFont } from './themeData.ts'
import type {
  BuiltInThemePresetId,
  ThemeModeDefinition,
  ThemeModes,
  ThemeProfileV2,
  ThemeVisibilitySlotId,
  ThemeWindowDefaults
} from './theme.ts'
import {
  THEME_PROFILE_SCHEMA_VERSION,
  TWILIGHT_DEFAULT_THEME,
  TWILIGHT_DEFAULT_THEME_ID
} from './themeTokens.ts'

export {
  THEME_DOCUMENT_SCHEMA_VERSION,
  THEME_PROFILE_SCHEMA_VERSION,
  TWILIGHT_DEFAULT_THEME_ID
} from './themeTokens.ts'
export const BUILT_IN_THEME_PRESET_IDS = [
  TWILIGHT_DEFAULT_THEME_ID,
  'builtin:aurora-reference',
  'builtin:obsidian-glass',
  'builtin:paper-light',
  'builtin:neon-gradient',
  'builtin:studio-split',
  'builtin:zen-minimal'
] as const
export const THEME_VISIBILITY_SLOT_IDS: readonly ThemeVisibilitySlotId[] = Object.freeze([
  'playerAlbumArtist',
  'playerArtwork',
  'playerTrackMenu',
  'playerMiscIcons',
  'playerDuration',
  'playerWaveform',
  'playerTrackInfo',
  'equalizerGrid',
  'equalizerFrequencyGuides',
  'equalizerSpectrum',
  'previousButton',
  'nextButton',
  'miniPlayerArtwork'
])
export const THEME_MODE_DEFINITIONS: readonly ThemeModeDefinition[] = Object.freeze([
  {
    id: 'appearance.accentSource',
    dataAttribute: 'data-te-accent-source',
    label: '强调色来源',
    options: ['fixed', 'cover'],
    defaultValue: 'fixed'
  },
  {
    id: 'appearance.backgroundTreatment',
    dataAttribute: 'data-te-background-treatment',
    label: '背景处理',
    options: ['solid', 'gradient', 'cover-blur', 'image'],
    defaultValue: 'solid'
  },
  {
    id: 'appearance.toneScheduling',
    dataAttribute: 'data-te-tone-scheduling',
    label: '明暗调度',
    options: ['manual', 'system', 'timed'],
    defaultValue: 'manual'
  },
  {
    id: 'appearance.contrastGuard',
    dataAttribute: 'data-te-contrast-guard',
    label: '对比度保护',
    options: ['off', 'warn', 'enforce'],
    defaultValue: 'warn'
  },
  {
    id: 'appearance.effectsMode',
    dataAttribute: 'data-te-effects-mode',
    label: '特效模式',
    options: ['full', 'reduced'],
    defaultValue: 'full'
  },
  {
    id: 'navigation.style',
    dataAttribute: 'data-te-navigation-style',
    label: '导航样式',
    options: ['expanded', 'compact', 'rail'],
    defaultValue: 'expanded'
  },
  {
    id: 'navigation.iconScale',
    dataAttribute: 'data-te-navigation-icon-scale',
    label: '导航图标大小',
    options: ['sm', 'md', 'lg'],
    defaultValue: 'md'
  },
  {
    id: 'navigation.logo',
    dataAttribute: 'data-te-navigation-logo',
    label: '导航品牌标识',
    options: ['show', 'hide'],
    defaultValue: 'hide'
  },
  {
    id: 'library.density',
    dataAttribute: 'data-te-library-density',
    label: '媒体库密度',
    options: ['comfortable', 'compact'],
    defaultValue: 'comfortable'
  },
  {
    id: 'library.selection',
    dataAttribute: 'data-te-library-selection',
    label: '媒体库选中样式',
    options: ['fill', 'stroke'],
    defaultValue: 'fill'
  },
  {
    id: 'library.titleOverlay',
    dataAttribute: 'data-te-library-title-overlay',
    label: '媒体库标题叠层',
    options: ['off', 'on'],
    defaultValue: 'off'
  },
  {
    id: 'player.layout',
    dataAttribute: 'data-te-player-layout',
    label: '播放器布局',
    options: ['standard', 'full-cover', 'lyrics-focus', 'split', 'minimal'],
    defaultValue: 'standard'
  },
  {
    id: 'player.controls',
    dataAttribute: 'data-te-player-controls',
    label: '播放器控制区',
    options: ['standard', 'pro'],
    defaultValue: 'standard'
  },
  {
    id: 'player.titleAlign',
    dataAttribute: 'data-te-player-title-align',
    label: '播放器标题对齐',
    options: ['left', 'center'],
    defaultValue: 'left'
  },
  {
    id: 'player.progress',
    dataAttribute: 'data-te-player-progress',
    label: '播放器进度样式',
    options: ['line', 'ring', 'solid', 'spectrum'],
    defaultValue: 'line'
  },
  {
    id: 'artwork.transition',
    dataAttribute: 'data-te-artwork-transition',
    label: '封面过渡',
    options: ['fade', 'slide', 'none'],
    defaultValue: 'fade'
  },
  {
    id: 'artwork.shadow',
    dataAttribute: 'data-te-artwork-shadow',
    label: '封面阴影',
    options: ['on', 'off'],
    defaultValue: 'on'
  },
  {
    id: 'equalizer.panel',
    dataAttribute: 'data-te-equalizer-panel',
    label: '均衡器面板',
    options: ['neutral', 'tinted', 'glass'],
    defaultValue: 'neutral'
  },
  {
    id: 'equalizer.slider',
    dataAttribute: 'data-te-equalizer-slider',
    label: '均衡器滑块',
    options: ['ring', 'solid'],
    defaultValue: 'ring'
  },
  {
    id: 'equalizer.knob',
    dataAttribute: 'data-te-equalizer-knob',
    label: '均衡器旋钮指示',
    options: ['line', 'dot'],
    defaultValue: 'line'
  },
  {
    id: 'equalizer.spectrum',
    dataAttribute: 'data-te-equalizer-spectrum',
    label: '均衡器频谱',
    options: ['bars', 'line', 'area'],
    defaultValue: 'line'
  },
  {
    id: 'equalizer.button',
    dataAttribute: 'data-te-equalizer-button',
    label: '均衡器按钮',
    options: ['soft', 'outline', 'solid'],
    defaultValue: 'soft'
  },
  {
    id: 'icons.family',
    dataAttribute: 'data-te-icon-family',
    label: '图标族',
    options: ['outline', 'rounded', 'filled'],
    defaultValue: 'outline'
  },
  {
    id: 'typography.titleCase',
    dataAttribute: 'data-te-title-case',
    label: '标题字形',
    options: ['preserve', 'uppercase'],
    defaultValue: 'preserve'
  },
  {
    id: 'typography.lyricAccent',
    dataAttribute: 'data-te-lyric-accent',
    label: '歌词强调高亮',
    options: ['off', 'accent'],
    defaultValue: 'off'
  },
  {
    id: 'typography.titleColor',
    dataAttribute: 'data-te-title-color',
    label: '自适应标题颜色',
    options: ['off', 'track', 'artist-album'],
    defaultValue: 'off'
  }
])
export const DEFAULT_THEME_MODES: Readonly<ThemeModes> = Object.freeze({
  appearance: Object.freeze({
    accentSource: 'fixed',
    backgroundTreatment: 'solid',
    toneScheduling: 'manual',
    contrastGuard: 'warn',
    effectsMode: 'full'
  }),
  navigation: Object.freeze({ style: 'expanded', iconScale: 'md', logo: 'hide' }),
  library: Object.freeze({ density: 'comfortable', selection: 'fill', titleOverlay: 'off' }),
  player: Object.freeze({
    layout: 'standard',
    controls: 'standard',
    titleAlign: 'left',
    progress: 'line'
  }),
  artwork: Object.freeze({ transition: 'fade', shadow: 'on' }),
  equalizer: Object.freeze({
    panel: 'neutral',
    slider: 'ring',
    knob: 'line',
    spectrum: 'line',
    button: 'soft'
  }),
  icons: Object.freeze({ family: 'outline' }),
  typography: Object.freeze({
    titleCase: 'preserve',
    lyricAccent: 'off',
    titleColor: 'off'
  }),
  visibility: Object.freeze({})
})
const allThemeVisibilitySlots = Object.freeze(
  Object.fromEntries(THEME_VISIBILITY_SLOT_IDS.map((id) => [id, true])) as Record<
    ThemeVisibilitySlotId,
    boolean
  >
)
function builtInThemePreset(
  id: BuiltInThemePresetId,
  name: string,
  description: string,
  overrides: ThemeProfileV2['overrides'],
  modes: ThemeModes,
  windowDefaults: ThemeWindowDefaults = {}
): ThemeProfileV2 {
  return Object.freeze({
    schemaVersion: THEME_PROFILE_SCHEMA_VERSION,
    id,
    name,
    description,
    baseThemeId: TWILIGHT_DEFAULT_THEME_ID,
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
    overrides,
    modes,
    windowDefaults
  })
}
export const BUILT_IN_THEME_PRESETS: readonly ThemeProfileV2[] = Object.freeze([
  builtInThemePreset(
    TWILIGHT_DEFAULT_THEME_ID,
    'Twilight Default',
    'Twilight Echo 的基准外观与完整功能可见性。',
    { pureWhite: {}, dark: {} },
    { visibility: { ...allThemeVisibilitySlots } },
    TWILIGHT_DEFAULT_THEME.windowDefaults
  ),
  builtInThemePreset(
    'builtin:aurora-reference',
    'Aurora 参考',
    '晨雾薄荷与极夜绿紫交织的光之幕，歌词悬浮在流动的极光辉光里呼吸。',
    {
      pureWhite: {
        'color.primary.500': '#0e9373',
        'color.primary.400': '#2fb392',
        'color.primary.300': '#9fe6cf',
        'color.primary.rgb': '14, 147, 115',
        'color.neutral.300': '#d9d5ee',
        'color.neutral.500': '#5d5c86',
        'color.neutral.700': '#403f68',
        'color.neutral.900': '#211f42',
        'surface.app': '#f3f1fc',
        'surface.local': '#f3f1fc',
        'surface.settings': '#f3f1fc',
        'surface.streaming': '#f3f1fc',
        'surface.player': '#eef1fa',
        'surface.card': 'rgba(255, 255, 255, 0.82)',
        'surface.cardBorder': 'rgba(255, 255, 255, 0.95)',
        'surface.hover': 'rgba(124, 138, 255, 0.09)',
        'surface.active': 'rgba(14, 147, 115, 0.14)',
        'background.gradientStart': '#e9e5fb',
        'background.gradientEnd': '#ddf5eb',
        'background.gradientAngle': '160deg',
        'background.coverBlur': '44px',
        'background.overlayOpacity': '20%',
        'material.glass': 'rgba(255, 255, 255, 0.72)',
        'material.glassStrong': 'rgba(255, 255, 255, 0.92)',
        'material.glassBorder': 'rgba(255, 255, 255, 0.88)',
        'material.glassShadow':
          '0 24px 70px rgba(122, 108, 228, 0.16), 0 0 44px rgba(64, 201, 162, 0.12)',
        'material.glowMain': 'rgba(64, 201, 162, 0.2)',
        'material.glowSoft': 'rgba(150, 132, 255, 0.16)',
        'material.glowCyan': 'rgba(94, 234, 212, 0.18)',
        'material.cardBlur': '28px',
        'typography.display':
          "'Space Grotesk', 'MiSans Full', 'MiSans', 'Microsoft YaHei UI', system-ui, sans-serif",
        'typography.titleWeight': '600',
        'typography.bodyWeight': '400',
        'shape.globalRadius': '18px',
        'shape.cardRadius': '22px',
        'navigation.surface': 'rgba(255, 255, 255, 0.58)',
        'navigation.activeSurface': 'rgba(14, 147, 115, 0.12)',
        'navigation.activeText': '#0b7a60',
        'navigation.indicator': '#0e9373',
        'navigation.radius': '22px',
        'navigation.opacity': '70%',
        'library.page.surface':
          'linear-gradient(180deg, rgba(255, 255, 255, 0.68), rgba(243, 241, 252, 0.52))',
        'library.table.surface': 'rgba(255, 255, 255, 0.42)',
        'library.row.text': '#403f68',
        'library.actionSurface': 'rgba(14, 147, 115, 0.1)',
        'library.coverRadius': '14px',
        'playback.accent': '#2fb392',
        'playback.backdrop.filter': 'blur(64px) saturate(1.4) brightness(0.55)',
        'playback.backdrop.scrim':
          'linear-gradient(180deg, rgba(24, 28, 56, 0.52) 0%, rgba(14, 34, 40, 0.6) 55%, rgba(9, 14, 32, 0.7) 100%)',
        'playback.cover.radius': '26px',
        'playback.cover.shadow':
          '0 30px 90px rgba(15, 20, 48, 0.42), 0 0 64px rgba(94, 234, 212, 0.28)',
        'playback.lyrics.activeSurface': 'rgba(94, 234, 212, 0.12)',
        'playback.lyrics.activeBorder': 'rgba(94, 234, 212, 0.3)',
        'playback.lyrics.activeShadow': '0 0 36px rgba(94, 234, 212, 0.32)',
        'playback.progress.track': 'rgba(255, 255, 255, 0.2)',
        'playback.progress.fill': 'linear-gradient(90deg, #5eead4, #a78bfa)',
        'playback.equalizer.sliderFill': 'linear-gradient(to top, #0e9373, #7c6cf0)',
        'playback.equalizer.spectrum': '#0e9373',
        'motion.enter': 'cubic-bezier(0.22, 1, 0.36, 1)',
        'motion.soft': 'cubic-bezier(0.16, 1, 0.3, 1)'
      },
      dark: {
        'color.primary.500': '#6ee7b7',
        'color.primary.400': '#9df0d0',
        'color.primary.300': '#c9f8e6',
        'color.primary.rgb': '110, 231, 183',
        'color.neutral.300': '#2d3157',
        'color.neutral.500': '#8f95c1',
        'color.neutral.700': '#c9cff2',
        'color.neutral.900': '#f1f4ff',
        'surface.app': '#0a0c1e',
        'surface.local': '#0a0c1e',
        'surface.settings': '#0a0c1e',
        'surface.streaming': '#0a0c1e',
        'surface.player': '#070812',
        'surface.card': 'rgba(22, 26, 52, 0.76)',
        'surface.cardBorder': 'rgba(110, 231, 183, 0.16)',
        'surface.hover': 'rgba(148, 163, 255, 0.08)',
        'surface.active': 'rgba(110, 231, 183, 0.14)',
        'background.gradientStart': '#111739',
        'background.gradientEnd': '#0a201e',
        'background.gradientAngle': '160deg',
        'background.coverBlur': '52px',
        'background.overlayOpacity': '46%',
        'material.glass': 'rgba(13, 16, 38, 0.7)',
        'material.glassStrong': 'rgba(15, 18, 42, 0.92)',
        'material.glassBorder': 'rgba(148, 163, 255, 0.14)',
        'material.glassShadow':
          '0 28px 80px rgba(2, 4, 16, 0.66), 0 0 52px rgba(110, 231, 183, 0.12)',
        'material.glowMain': 'rgba(110, 231, 183, 0.22)',
        'material.glowSoft': 'rgba(167, 139, 250, 0.18)',
        'material.glowCyan': 'rgba(103, 232, 249, 0.14)',
        'material.cardBlur': '30px',
        'typography.display':
          "'Space Grotesk', 'MiSans Full', 'MiSans', 'Microsoft YaHei UI', system-ui, sans-serif",
        'typography.titleWeight': '600',
        'typography.bodyWeight': '400',
        'shape.globalRadius': '18px',
        'shape.cardRadius': '22px',
        'navigation.surface': 'rgba(9, 12, 30, 0.62)',
        'navigation.activeSurface': 'rgba(110, 231, 183, 0.14)',
        'navigation.activeText': '#6ee7b7',
        'navigation.indicator': '#6ee7b7',
        'navigation.radius': '22px',
        'navigation.opacity': '82%',
        'library.page.surface':
          'linear-gradient(180deg, rgba(17, 21, 46, 0.72), rgba(8, 10, 26, 0.58))',
        'library.table.surface': 'rgba(20, 24, 52, 0.44)',
        'library.row.text': '#c9cff2',
        'library.actionSurface': 'rgba(110, 231, 183, 0.12)',
        'library.coverRadius': '14px',
        'playback.accent': '#6ee7b7',
        'playback.backdrop.filter': 'blur(64px) saturate(1.5) brightness(0.3)',
        'playback.backdrop.scrim':
          'linear-gradient(180deg, rgba(4, 6, 18, 0.66) 0%, rgba(6, 14, 26, 0.72) 55%, rgba(2, 4, 12, 0.8) 100%)',
        'playback.cover.radius': '26px',
        'playback.cover.shadow':
          '0 30px 90px rgba(0, 0, 0, 0.6), 0 0 70px rgba(110, 231, 183, 0.24)',
        'playback.lyrics.activeSurface': 'rgba(110, 231, 183, 0.1)',
        'playback.lyrics.activeBorder': 'rgba(110, 231, 183, 0.26)',
        'playback.lyrics.activeShadow': '0 0 40px rgba(110, 231, 183, 0.3)',
        'playback.progress.track': 'rgba(255, 255, 255, 0.16)',
        'playback.progress.fill': 'linear-gradient(90deg, #6ee7b7, #a78bfa)',
        'playback.equalizer.sliderFill': 'linear-gradient(to top, #6ee7b7, #a78bfa)',
        'playback.equalizer.spectrum': '#6ee7b7',
        'motion.enter': 'cubic-bezier(0.22, 1, 0.36, 1)',
        'motion.soft': 'cubic-bezier(0.16, 1, 0.3, 1)'
      }
    },
    {
      appearance: {
        accentSource: 'cover',
        backgroundTreatment: 'cover-blur',
        toneScheduling: 'timed',
        contrastGuard: 'enforce',
        effectsMode: 'full'
      },
      navigation: { style: 'expanded', iconScale: 'md', logo: 'hide' },
      library: { density: 'comfortable', selection: 'fill', titleOverlay: 'on' },
      player: {
        layout: 'lyrics-focus',
        controls: 'standard',
        titleAlign: 'center',
        progress: 'ring'
      },
      artwork: { transition: 'fade', shadow: 'on' },
      equalizer: { panel: 'glass', slider: 'ring', knob: 'dot', spectrum: 'area', button: 'soft' },
      icons: { family: 'rounded' },
      typography: { titleCase: 'preserve', lyricAccent: 'accent', titleColor: 'track' },
      visibility: { ...allThemeVisibilitySlots, playerWaveform: false, playerMiscIcons: false }
    },
    {
      miniPlayer: {
        surfaceColor: '#0b0e22',
        accentColor: '#6ee7b7',
        primaryTextColor: '#f1f4ff',
        mutedTextColor: '#aab1d6',
        fontFamily: lightFont,
        surfaceOpacity: 78,
        glassBlur: 32,
        cornerRadius: 24,
        borderWidth: 1,
        borderColor: '#2d3157',
        shadowStrength: 78,
        shadowColor: '#020410'
      },
      desktopLyrics: {
        fontFamily:
          "'Space Grotesk', 'MiSans Full', 'MiSans', 'Microsoft YaHei UI', system-ui, sans-serif",
        fontSize: 34,
        fontWeight: 600,
        color: '#e6ebff',
        highlightColor: '#6ee7b7',
        backgroundColor: '#0a0c1e',
        backgroundOpacity: 34,
        shadow: true,
        shadowBlur: 14,
        shadowColor: '#04101c'
      }
    }
  ),
  builtInThemePreset(
    'builtin:obsidian-glass',
    'Obsidian Glass',
    '深渊般的纯黑玻璃与冰青断口微光，在厚重阴影中折射出锋利而克制的奢华。',
    {
      pureWhite: {
        'color.primary.500': '#67e8f9',
        'color.primary.400': '#a5f3fc',
        'color.primary.300': '#cffafe',
        'color.primary.rgb': '103, 232, 249',
        'color.accentCyan': '#67e8f9',
        'color.neutral.50': '#030405',
        'color.neutral.100': '#0b0e10',
        'color.neutral.200': '#181d20',
        'color.neutral.300': '#262d31',
        'color.neutral.500': '#93a1a6',
        'color.neutral.700': '#ccd6da',
        'color.neutral.900': '#f0f5f6',
        'surface.app': '#0b0d10',
        'surface.local': '#0b0d10',
        'surface.settings': '#0b0d10',
        'surface.streaming': '#0b0d10',
        'surface.player': '#07090b',
        'surface.card': '#12161a',
        'surface.cardBorder': 'rgba(148, 220, 233, 0.17)',
        'surface.subtle': '#0e1114',
        'surface.hover': 'rgba(165, 243, 252, 0.06)',
        'surface.active': 'rgba(103, 232, 249, 0.14)',
        'background.gradientStart': '#101418',
        'background.gradientEnd': '#07090b',
        'background.gradientAngle': '168deg',
        'shell.control.text': '#f0f5f6',
        'shell.control.hoverSurface': 'rgba(165, 243, 252, 0.08)',
        'settings.text.primary': '#f0f5f6',
        'settings.text.muted': '#93a1a6',
        'settings.control.surface': '#12161a',
        'settings.control.border': 'rgba(148, 220, 233, 0.14)',
        'settings.navigation.text': '#93a1a6',
        'settings.navigation.hoverSurface': 'rgba(165, 243, 252, 0.06)',
        'settings.navigation.activeSurface': 'rgba(103, 232, 249, 0.14)',
        'navigation.surface': 'rgba(7, 9, 11, 0.92)',
        'navigation.border': 'rgba(148, 220, 233, 0.12)',
        'navigation.shadow': '8px 0 36px rgba(0, 0, 0, 0.6)',
        'navigation.text': '#ccd6da',
        'navigation.icon': '#93a1a6',
        'navigation.hoverSurface': 'rgba(165, 243, 252, 0.07)',
        'navigation.hoverText': '#f0f5f6',
        'navigation.activeSurface': 'rgba(103, 232, 249, 0.14)',
        'navigation.activeText': '#67e8f9',
        'navigation.indicator': '#67e8f9',
        'library.row.text': '#ccd6da',
        'library.row.hoverSurface': 'rgba(165, 243, 252, 0.05)',
        'library.selection.surface': 'rgba(103, 232, 249, 0.1)',
        'library.selection.hoverSurface': 'rgba(103, 232, 249, 0.16)',
        'library.selection.indicator': '#67e8f9',
        'library.icon': '#93a1a6',
        'typography.display': "'Space Grotesk', 'MiSans Full', 'MiSans', system-ui, sans-serif",
        'typography.chromeText': '#ccd6da',
        'shape.globalRadius': '12px',
        'shape.cardRadius': '14px',
        'material.glass': 'rgba(11, 14, 17, 0.78)',
        'material.glassStrong': 'rgba(8, 10, 13, 0.92)',
        'material.glassBorder': 'rgba(148, 220, 233, 0.15)',
        'material.glassShadow': '0 26px 72px rgba(0, 0, 0, 0.64)',
        'material.glowMain': 'rgba(103, 232, 249, 0.16)',
        'material.cardBlur': '28px',
        'playback.accent': '#67e8f9',
        'playback.backdrop.filter': 'blur(72px) saturate(1.04) brightness(0.3)',
        'playback.cover.radius': '14px',
        'playback.cover.shadow':
          '0 34px 90px rgba(0, 0, 0, 0.72), inset 0 0 0 1px rgba(165, 243, 252, 0.14)',
        'playback.control.radius': '12px',
        'playback.progress.height': '3px',
        'playback.progress.track': 'rgba(165, 243, 252, 0.14)',
        'playback.progress.fill': 'linear-gradient(90deg, #22d3ee, #a5f3fc)',
        'playback.equalizer.sliderFill': 'linear-gradient(to top, #0e7490, #67e8f9)',
        'playback.equalizer.spectrum': '#67e8f9',
        'playback.equalizer.guide': 'rgba(103, 232, 249, 0.5)'
      },
      dark: {
        'color.primary.500': '#22d3ee',
        'color.primary.400': '#67e8f9',
        'color.primary.300': '#a5f3fc',
        'color.primary.rgb': '34, 211, 238',
        'color.accentCyan': '#22d3ee',
        'color.neutral.50': '#000000',
        'color.neutral.100': '#070809',
        'color.neutral.200': '#121517',
        'color.neutral.300': '#1f2427',
        'color.neutral.500': '#8a969b',
        'color.neutral.700': '#c6d1d5',
        'color.neutral.900': '#edf3f5',
        'surface.app': '#040506',
        'surface.local': '#040506',
        'surface.settings': '#040506',
        'surface.streaming': '#040506',
        'surface.player': '#020304',
        'surface.card': '#0b0e11',
        'surface.cardBorder': 'rgba(134, 213, 227, 0.15)',
        'surface.subtle': '#080a0c',
        'surface.hover': 'rgba(165, 243, 252, 0.05)',
        'surface.active': 'rgba(34, 211, 238, 0.14)',
        'background.gradientStart': '#0a0d10',
        'background.gradientEnd': '#020304',
        'background.gradientAngle': '168deg',
        'shell.control.text': '#edf3f5',
        'shell.control.hoverSurface': 'rgba(165, 243, 252, 0.07)',
        'settings.text.primary': '#edf3f5',
        'settings.text.muted': '#8a969b',
        'settings.control.surface': '#0b0e11',
        'settings.control.border': 'rgba(134, 213, 227, 0.12)',
        'settings.navigation.text': '#8a969b',
        'settings.navigation.hoverSurface': 'rgba(165, 243, 252, 0.05)',
        'settings.navigation.activeSurface': 'rgba(34, 211, 238, 0.15)',
        'navigation.surface': 'rgba(2, 3, 4, 0.94)',
        'navigation.border': 'rgba(134, 213, 227, 0.1)',
        'navigation.shadow': '8px 0 36px rgba(0, 0, 0, 0.7)',
        'navigation.text': '#c6d1d5',
        'navigation.icon': '#8a969b',
        'navigation.hoverSurface': 'rgba(165, 243, 252, 0.06)',
        'navigation.hoverText': '#edf3f5',
        'navigation.activeSurface': 'rgba(34, 211, 238, 0.15)',
        'navigation.activeText': '#22d3ee',
        'navigation.indicator': '#22d3ee',
        'library.row.text': '#c6d1d5',
        'library.row.hoverSurface': 'rgba(165, 243, 252, 0.045)',
        'library.selection.surface': 'rgba(34, 211, 238, 0.1)',
        'library.selection.hoverSurface': 'rgba(34, 211, 238, 0.16)',
        'library.selection.indicator': '#22d3ee',
        'library.icon': '#8a969b',
        'typography.display': "'Space Grotesk', 'MiSans Full', 'MiSans', system-ui, sans-serif",
        'typography.chromeText': '#c6d1d5',
        'shape.globalRadius': '12px',
        'shape.cardRadius': '14px',
        'material.glass': 'rgba(5, 7, 9, 0.82)',
        'material.glassStrong': 'rgba(3, 4, 5, 0.94)',
        'material.glassBorder': 'rgba(134, 213, 227, 0.13)',
        'material.glassShadow': '0 28px 80px rgba(0, 0, 0, 0.78)',
        'material.glowMain': 'rgba(34, 211, 238, 0.18)',
        'material.cardBlur': '30px',
        'playback.accent': '#22d3ee',
        'playback.backdrop.filter': 'blur(76px) saturate(1.02) brightness(0.24)',
        'playback.cover.radius': '14px',
        'playback.cover.shadow':
          '0 38px 100px rgba(0, 0, 0, 0.82), inset 0 0 0 1px rgba(165, 243, 252, 0.12)',
        'playback.control.radius': '12px',
        'playback.progress.height': '3px',
        'playback.progress.track': 'rgba(165, 243, 252, 0.12)',
        'playback.progress.fill': 'linear-gradient(90deg, #06b6d4, #a5f3fc)',
        'playback.equalizer.sliderFill': 'linear-gradient(to top, #155e75, #22d3ee)',
        'playback.equalizer.spectrum': '#22d3ee',
        'playback.equalizer.guide': 'rgba(34, 211, 238, 0.5)'
      }
    },
    {
      appearance: {
        accentSource: 'fixed',
        backgroundTreatment: 'gradient',
        contrastGuard: 'enforce',
        effectsMode: 'full'
      },
      navigation: { style: 'rail', iconScale: 'md', logo: 'hide' },
      library: { density: 'compact', selection: 'stroke', titleOverlay: 'off' },
      player: { layout: 'full-cover', controls: 'pro', titleAlign: 'left', progress: 'line' },
      artwork: { transition: 'fade', shadow: 'on' },
      equalizer: {
        panel: 'glass',
        slider: 'solid',
        knob: 'dot',
        spectrum: 'area',
        button: 'outline'
      },
      icons: { family: 'filled' },
      typography: { titleCase: 'uppercase', lyricAccent: 'accent', titleColor: 'off' },
      visibility: {
        ...allThemeVisibilitySlots,
        playerAlbumArtist: false,
        playerTrackMenu: false,
        playerMiscIcons: false,
        playerDuration: false,
        playerWaveform: false
      }
    },
    {
      miniPlayer: {
        surfaceColor: '#040506',
        accentColor: '#22d3ee',
        primaryTextColor: '#edf3f5',
        mutedTextColor: '#8a969b',
        fontFamily: lightFont,
        surfaceOpacity: 78,
        glassBlur: 34,
        cornerRadius: 14,
        borderWidth: 1,
        borderColor: '#1c3b42',
        shadowStrength: 96,
        shadowColor: '#000000'
      },
      desktopLyrics: {
        fontFamily: "'Space Grotesk', 'MiSans Full', 'MiSans', system-ui, sans-serif",
        fontSize: 30,
        fontWeight: 600,
        color: '#dfe9eb',
        highlightColor: '#22d3ee',
        backgroundColor: '#020304',
        backgroundOpacity: 56,
        shadow: true,
        shadowBlur: 14,
        shadowColor: '#000000'
      }
    }
  ),
  builtInThemePreset(
    'builtin:paper-light',
    'Paper Light',
    '暖纸底色、衬线标题与朱砂细线的排印之作，以边线代替阴影与光晕，安静克制如一页夜读的杂志。',
    {
      pureWhite: {
        'color.primary.500': '#a8321f',
        'color.primary.400': '#c14e37',
        'color.primary.rgb': '168, 50, 31',
        'color.neutral.200': '#e3dcca',
        'color.neutral.500': '#6d675a',
        'color.neutral.700': '#3b362b',
        'color.neutral.900': '#211d15',
        'surface.app': '#f6f2e9',
        'surface.local': '#f6f2e9',
        'surface.settings': '#f6f2e9',
        'surface.streaming': '#f6f2e9',
        'surface.player': '#f6f2e9',
        'surface.card': '#fcfaf3',
        'surface.cardBorder': '#d9d2c0',
        'surface.hover': '#efe9db',
        'navigation.surface': '#f6f2e9',
        'navigation.border': '#d9d2c0',
        'navigation.activeSurface': 'rgba(168, 50, 31, 0.07)',
        'navigation.activeText': '#a8321f',
        'navigation.indicator': '#a8321f',
        'library.table.surface': '#fcfaf3',
        'library.table.border': '#d9d2c0',
        'library.table.shadow': 'none',
        'library.selection.indicator': '#a8321f',
        'library.selection.radius': '2px',
        'library.coverRadius': '2px',
        'material.glass': '#fcfaf3',
        'material.glassBorder': '#d9d2c0',
        'material.glassShadow': 'none',
        'material.cardBlur': '0px',
        'typography.display': "'Lora', 'Noto Serif SC', 'Source Han Serif SC', Georgia, serif",
        'typography.titleWeight': '600',
        'typography.chromeText': '#4a4436',
        'shape.globalRadius': '3px',
        'shape.cardRadius': '3px',
        'playback.accent': '#a8321f',
        'playback.text.page': '#211d15',
        'playback.backdrop.scrim':
          'linear-gradient(180deg, rgba(246, 242, 233, 0.95) 0%, rgba(246, 242, 233, 0.96) 55%, rgba(242, 237, 225, 0.98) 100%)',
        'playback.cover.radius': '2px',
        'playback.cover.shadow': 'none',
        'playback.track.title': '#211d15',
        'playback.track.artist': 'rgba(33, 29, 21, 0.72)',
        'playback.track.album': 'rgba(33, 29, 21, 0.52)',
        'playback.lyrics.text': 'rgba(33, 29, 21, 0.45)',
        'playback.lyrics.hoverText': 'rgba(33, 29, 21, 0.68)',
        'playback.lyrics.activeText': '#211d15',
        'playback.lyrics.activeSurface': 'transparent',
        'playback.lyrics.activeShadow': 'none',
        'playback.lyrics.translation': 'rgba(33, 29, 21, 0.56)',
        'playback.lyrics.translationActive': 'rgba(33, 29, 21, 0.8)',
        'playback.control.border': 'rgba(33, 29, 21, 0.3)',
        'playback.control.text': 'rgba(33, 29, 21, 0.78)',
        'playback.control.hoverSurface': 'rgba(33, 29, 21, 0.06)',
        'playback.control.hoverText': '#211d15',
        'playback.control.radius': '2px',
        'playback.progress.track': 'rgba(33, 29, 21, 0.16)',
        'playback.progress.fill': 'linear-gradient(90deg, #a8321f, #a8321f)',
        'playback.progress.height': '3px',
        'playback.equalizer.sliderFill': 'linear-gradient(to top, #a8321f, #c14e37)',
        'playback.equalizer.spectrum': '#a8321f'
      },
      dark: {
        'color.primary.500': '#cc8060',
        'color.primary.400': '#d99877',
        'color.primary.rgb': '204, 128, 96',
        'color.neutral.200': '#382f24',
        'color.neutral.500': '#a2967f',
        'color.neutral.700': '#d7cbb2',
        'color.neutral.900': '#efe6d2',
        'surface.app': '#231d16',
        'surface.local': '#231d16',
        'surface.settings': '#231d16',
        'surface.streaming': '#231d16',
        'surface.player': '#231d16',
        'surface.card': '#2b241b',
        'surface.cardBorder': '#463c2d',
        'surface.hover': 'rgba(239, 230, 210, 0.06)',
        'surface.active': 'rgba(204, 128, 96, 0.16)',
        'navigation.surface': '#231d16',
        'navigation.border': '#463c2d',
        'navigation.activeSurface': 'rgba(204, 128, 96, 0.12)',
        'navigation.activeText': '#cc8060',
        'navigation.indicator': '#cc8060',
        'library.table.surface': '#2b241b',
        'library.table.border': '#463c2d',
        'library.table.shadow': 'none',
        'library.selection.indicator': '#cc8060',
        'library.selection.radius': '2px',
        'library.coverRadius': '2px',
        'material.glass': '#2b241b',
        'material.glassBorder': '#463c2d',
        'material.glassShadow': 'none',
        'material.cardBlur': '0px',
        'typography.display': "'Lora', 'Noto Serif SC', 'Source Han Serif SC', Georgia, serif",
        'typography.titleWeight': '600',
        'typography.chromeText': '#cdc0a6',
        'shape.globalRadius': '3px',
        'shape.cardRadius': '3px',
        'playback.accent': '#cc8060',
        'playback.text.page': '#efe6d2',
        'playback.backdrop.scrim':
          'linear-gradient(180deg, rgba(35, 29, 22, 0.95) 0%, rgba(35, 29, 22, 0.96) 55%, rgba(28, 23, 17, 0.98) 100%)',
        'playback.cover.radius': '2px',
        'playback.cover.shadow': 'none',
        'playback.track.title': '#f4ecda',
        'playback.track.artist': 'rgba(239, 230, 210, 0.74)',
        'playback.track.album': 'rgba(239, 230, 210, 0.5)',
        'playback.lyrics.text': 'rgba(239, 230, 210, 0.42)',
        'playback.lyrics.hoverText': 'rgba(239, 230, 210, 0.7)',
        'playback.lyrics.activeText': '#f4ecda',
        'playback.lyrics.activeSurface': 'transparent',
        'playback.lyrics.activeShadow': 'none',
        'playback.lyrics.translation': 'rgba(239, 230, 210, 0.58)',
        'playback.lyrics.translationActive': 'rgba(239, 230, 210, 0.82)',
        'playback.control.border': 'rgba(239, 230, 210, 0.28)',
        'playback.control.text': 'rgba(239, 230, 210, 0.8)',
        'playback.control.hoverText': '#f4ecda',
        'playback.control.radius': '2px',
        'playback.progress.track': 'rgba(239, 230, 210, 0.18)',
        'playback.progress.fill': 'linear-gradient(90deg, #cc8060, #cc8060)',
        'playback.progress.height': '3px',
        'playback.equalizer.sliderFill': 'linear-gradient(to top, #cc8060, #d99877)',
        'playback.equalizer.spectrum': '#cc8060'
      }
    },
    {
      appearance: {
        backgroundTreatment: 'solid',
        contrastGuard: 'enforce',
        effectsMode: 'reduced'
      },
      navigation: { style: 'expanded', iconScale: 'sm', logo: 'show' },
      library: { density: 'comfortable', selection: 'stroke', titleOverlay: 'off' },
      player: { layout: 'standard', controls: 'standard', titleAlign: 'left', progress: 'line' },
      artwork: { transition: 'none', shadow: 'off' },
      equalizer: {
        panel: 'neutral',
        slider: 'solid',
        knob: 'line',
        spectrum: 'line',
        button: 'outline'
      },
      icons: { family: 'outline' },
      typography: { titleCase: 'preserve', lyricAccent: 'accent', titleColor: 'off' },
      visibility: { ...allThemeVisibilitySlots, playerWaveform: false, playerMiscIcons: false }
    },
    {
      miniPlayer: {
        surfaceColor: '#f6f2e9',
        accentColor: '#a8321f',
        primaryTextColor: '#211d15',
        mutedTextColor: '#6d675a',
        fontFamily: "'Lora', 'Noto Serif SC', 'Source Han Serif SC', Georgia, serif",
        surfaceOpacity: 100,
        glassBlur: 0,
        cornerRadius: 3,
        borderWidth: 1,
        borderColor: '#d9d2c0',
        shadowStrength: 0,
        shadowColor: '#000000'
      },
      desktopLyrics: {
        fontFamily: "'Lora', 'Noto Serif SC', 'Source Han Serif SC', Georgia, serif",
        fontSize: 30,
        fontWeight: 500,
        color: '#211d15',
        highlightColor: '#a8321f',
        backgroundColor: '#f6f2e9',
        backgroundOpacity: 96,
        shadow: false,
        shadowBlur: 0,
        shadowColor: '#000000'
      }
    }
  ),
  builtInThemePreset(
    'builtin:neon-gradient',
    'Neon Gradient',
    '霓虹夜城：品红与电青的双色电流点亮近黑紫夜幕，药丸圆角与彩色辉光让整座界面彻夜发光。',
    {
      pureWhite: {
        'color.primary.500': '#db1f8e',
        'color.primary.400': '#ef4aae',
        'color.primary.rgb': '219, 31, 142',
        'color.accentCyan': '#00b3d7',
        'color.neutral.900': '#2b0a45',
        'color.neutral.700': '#54246f',
        'color.neutral.500': '#7d4899',
        'surface.app': '#fdf2fc',
        'surface.local': '#fdf2fc',
        'surface.settings': '#fdf2fc',
        'surface.streaming': '#fdf2fc',
        'surface.player': '#fdf2fc',
        'surface.card': '#ffffff',
        'surface.cardBorder': 'rgba(219, 31, 142, 0.22)',
        'surface.subtle': '#fce8f9',
        'surface.hover': 'rgba(219, 31, 142, 0.07)',
        'surface.active': 'rgba(219, 31, 142, 0.15)',
        'background.gradientStart': '#ffbfe6',
        'background.gradientEnd': '#aaefff',
        'background.gradientAngle': '128deg',
        'shell.control.hoverSurface': 'rgba(219, 31, 142, 0.1)',
        'navigation.surface': 'rgba(255, 255, 255, 0.82)',
        'navigation.border': 'rgba(219, 31, 142, 0.16)',
        'navigation.text': '#6d3f8a',
        'navigation.activeSurface': 'rgba(219, 31, 142, 0.14)',
        'navigation.activeText': '#b3126f',
        'navigation.indicator': '#00b3d7',
        'navigation.radius': '26px',
        'material.glass': 'rgba(255, 255, 255, 0.86)',
        'material.glassStrong': 'rgba(255, 255, 255, 0.96)',
        'material.glassBorder': 'rgba(219, 31, 142, 0.2)',
        'material.glassShadow':
          '0 20px 55px rgba(219, 31, 142, 0.18), 0 8px 28px rgba(0, 179, 215, 0.12)',
        'material.glowMain': 'rgba(219, 31, 142, 0.22)',
        'material.glowSoft': 'rgba(0, 179, 215, 0.16)',
        'material.cardBlur': '24px',
        'typography.display':
          "'Space Grotesk', 'MiSans Full', 'MiSans', 'Microsoft YaHei UI', system-ui, sans-serif",
        'typography.titleWeight': '800',
        'typography.metaWeight': '500',
        'shape.globalRadius': '24px',
        'shape.cardRadius': '24px',
        'shape.searchRadius': '24px',
        'playback.accent': '#ff3fa4',
        'playback.cover.radius': '32px',
        'playback.cover.shadow':
          '0 30px 84px rgba(219, 31, 142, 0.42), 0 12px 40px rgba(0, 179, 215, 0.26)',
        'playback.progress.fill': 'linear-gradient(90deg, #ff2d96, #22e0ff)',
        'playback.progress.track': 'rgba(255, 63, 164, 0.2)',
        'playback.control.playSize': '56px',
        'playback.equalizer.panelBorder': 'rgba(219, 31, 142, 0.22)',
        'playback.equalizer.panelRadius': '28px',
        'playback.equalizer.sliderFill': 'linear-gradient(to top, #db1f8e, #00b3d7)',
        'playback.equalizer.spectrum': '#db1f8e',
        'playback.equalizer.buttonSurface': 'rgba(219, 31, 142, 0.12)',
        'playback.equalizer.buttonRadius': '18px',
        'library.row.text': '#54246f',
        'library.selection.surface': 'rgba(219, 31, 142, 0.12)',
        'library.selection.indicator': '#db1f8e',
        'library.selection.radius': '18px',
        'library.coverRadius': '18px',
        'motion.enter': 'cubic-bezier(0.16, 1, 0.3, 1)'
      },
      dark: {
        'color.primary.500': '#ff3fa4',
        'color.primary.400': '#ff74bf',
        'color.primary.rgb': '255, 63, 164',
        'color.accentCyan': '#22e0ff',
        'color.neutral.900': '#fdeefb',
        'color.neutral.700': '#e6cdef',
        'color.neutral.500': '#b98fd0',
        'surface.app': '#0b0514',
        'surface.local': '#0b0514',
        'surface.settings': '#0b0514',
        'surface.streaming': '#0b0514',
        'surface.player': '#080310',
        'surface.card': '#170b26',
        'surface.cardBorder': 'rgba(255, 63, 164, 0.3)',
        'surface.subtle': '#120820',
        'surface.hover': 'rgba(255, 63, 164, 0.1)',
        'surface.active': 'rgba(255, 63, 164, 0.2)',
        'background.gradientStart': '#4c0a6f',
        'background.gradientEnd': '#043c54',
        'background.gradientAngle': '128deg',
        'shell.control.hoverSurface': 'rgba(255, 63, 164, 0.16)',
        'navigation.surface': 'rgba(17, 7, 30, 0.88)',
        'navigation.border': 'rgba(255, 63, 164, 0.22)',
        'navigation.text': '#cbaed9',
        'navigation.activeSurface': 'rgba(255, 63, 164, 0.22)',
        'navigation.activeText': '#ffa3d8',
        'navigation.indicator': '#22e0ff',
        'navigation.radius': '26px',
        'material.glass': 'rgba(23, 11, 38, 0.82)',
        'material.glassStrong': 'rgba(28, 13, 46, 0.95)',
        'material.glassBorder': 'rgba(255, 63, 164, 0.26)',
        'material.glassShadow':
          '0 24px 64px rgba(255, 45, 150, 0.28), 0 10px 34px rgba(34, 224, 255, 0.16)',
        'material.glowMain': 'rgba(255, 63, 164, 0.38)',
        'material.glowSoft': 'rgba(34, 224, 255, 0.24)',
        'material.cardBlur': '26px',
        'typography.display':
          "'Space Grotesk', 'MiSans Full', 'MiSans', 'Microsoft YaHei UI', system-ui, sans-serif",
        'typography.titleWeight': '800',
        'typography.metaWeight': '500',
        'shape.globalRadius': '24px',
        'shape.cardRadius': '24px',
        'shape.searchRadius': '24px',
        'playback.accent': '#ff3fa4',
        'playback.cover.radius': '32px',
        'playback.cover.shadow':
          '0 32px 90px rgba(255, 45, 150, 0.5), 0 12px 44px rgba(34, 224, 255, 0.32)',
        'playback.progress.fill': 'linear-gradient(90deg, #ff2d96, #22e0ff)',
        'playback.progress.track': 'rgba(255, 63, 164, 0.2)',
        'playback.control.playSize': '56px',
        'playback.equalizer.panelBorder': 'rgba(255, 63, 164, 0.3)',
        'playback.equalizer.panelRadius': '28px',
        'playback.equalizer.sliderFill': 'linear-gradient(to top, #ff2d96, #22e0ff)',
        'playback.equalizer.spectrum': '#22e0ff',
        'playback.equalizer.buttonSurface': 'rgba(255, 63, 164, 0.2)',
        'playback.equalizer.buttonRadius': '18px',
        'library.row.text': '#e6cdef',
        'library.selection.surface': 'rgba(255, 63, 164, 0.2)',
        'library.selection.indicator': '#22e0ff',
        'library.selection.radius': '18px',
        'library.coverRadius': '18px',
        'motion.enter': 'cubic-bezier(0.16, 1, 0.3, 1)'
      }
    },
    {
      appearance: { backgroundTreatment: 'gradient', contrastGuard: 'enforce' },
      navigation: { style: 'compact', iconScale: 'lg', logo: 'hide' },
      library: { density: 'compact', selection: 'fill', titleOverlay: 'on' },
      player: { layout: 'minimal', controls: 'pro', titleAlign: 'center', progress: 'spectrum' },
      artwork: { transition: 'slide', shadow: 'on' },
      equalizer: {
        panel: 'tinted',
        slider: 'solid',
        knob: 'dot',
        spectrum: 'bars',
        button: 'solid'
      },
      icons: { family: 'filled' },
      typography: { titleCase: 'uppercase', lyricAccent: 'accent', titleColor: 'track' },
      visibility: {
        ...allThemeVisibilitySlots,
        playerAlbumArtist: false,
        playerTrackMenu: false,
        playerMiscIcons: false,
        playerDuration: false,
        playerWaveform: false,
        equalizerGrid: false,
        equalizerFrequencyGuides: false
      }
    },
    {
      miniPlayer: {
        surfaceColor: '#12061e',
        accentColor: '#ff3fa4',
        primaryTextColor: '#fdeefb',
        mutedTextColor: '#cbaed9',
        fontFamily:
          "'Space Grotesk', 'MiSans Full', 'MiSans', 'Microsoft YaHei UI', system-ui, sans-serif",
        surfaceOpacity: 84,
        glassBlur: 28,
        cornerRadius: 32,
        borderWidth: 1,
        borderColor: '#ff3fa4',
        shadowStrength: 90,
        shadowColor: '#2b0040'
      },
      desktopLyrics: {
        fontFamily:
          "'Space Grotesk', 'MiSans Full', 'MiSans', 'Microsoft YaHei UI', system-ui, sans-serif",
        fontSize: 34,
        fontWeight: 800,
        color: '#fdeefb',
        highlightColor: '#22e0ff',
        backgroundColor: '#12061e',
        backgroundOpacity: 46,
        shadow: true,
        shadowBlur: 16,
        shadowColor: '#ff2d96'
      }
    }
  ),
  builtInThemePreset(
    'builtin:studio-split',
    'Studio Split',
    '机架灰哑光面板、等宽刻度字与信号色仪表线构成的录音棚控制台。',
    {
      pureWhite: {
        'color.primary.500': '#c2410c',
        'color.primary.400': '#ea580c',
        'color.primary.300': '#fdba74',
        'color.primary.rgb': '194, 65, 12',
        'color.favorite': '#dc2626',
        'color.warning': '#b45309',
        'color.neutral.200': '#d4d8da',
        'color.neutral.300': '#b6bcbf',
        'color.neutral.500': '#5b6467',
        'color.neutral.700': '#333a3d',
        'color.neutral.900': '#14181a',
        'surface.app': '#e9ebec',
        'surface.local': '#e9ebec',
        'surface.settings': '#e9ebec',
        'surface.streaming': '#e9ebec',
        'surface.player': '#e9ebec',
        'surface.card': '#f4f5f6',
        'surface.cardBorder': '#c6cbcd',
        'surface.subtle': '#eef0f1',
        'surface.hover': '#e2e5e6',
        'surface.active': 'rgba(194, 65, 12, 0.1)',
        'material.glass': '#f4f5f6',
        'material.glassStrong': '#fafbfb',
        'material.glassBorder': '#c6cbcd',
        'material.glassShadow': 'none',
        'material.cardBlur': '0px',
        'material.cardSaturation': '100%',
        'material.glowMain': 'transparent',
        'navigation.surface': '#e2e5e6',
        'navigation.border': '#c6cbcd',
        'navigation.shadow': 'none',
        'navigation.activeSurface': 'rgba(194, 65, 12, 0.1)',
        'navigation.activeText': '#c2410c',
        'navigation.indicator': '#c2410c',
        'typography.sans': "'JetBrains Mono', 'Cascadia Code', 'MiSans', Consolas, monospace",
        'typography.display': "'JetBrains Mono', 'Cascadia Code', 'MiSans', Consolas, monospace",
        'typography.titleWeight': '600',
        'typography.bodyWeight': '400',
        'typography.bodySize': '13px',
        'shape.globalRadius': '4px',
        'shape.cardRadius': '6px',
        'motion.enter': 'cubic-bezier(0.2, 0, 0.4, 1)',
        'motion.soft': 'linear',
        'library.table.shadow': 'none',
        'library.selection.indicator': '#c2410c',
        'library.selection.radius': '2px',
        'library.coverRadius': '2px',
        'playback.accent': '#fb923c',
        'playback.backdrop.filter': 'blur(72px) saturate(0.55) brightness(0.4)',
        'playback.backdrop.scrim':
          'linear-gradient(180deg, rgba(12, 14, 15, 0.78), rgba(12, 14, 15, 0.82))',
        'playback.cover.radius': '4px',
        'playback.control.radius': '4px',
        'playback.control.borderWidth': '1px',
        'playback.progress.fill': 'linear-gradient(90deg, #fb923c, #fb923c)',
        'playback.progress.height': '3px',
        'playback.progress.radius': '0px',
        'playback.equalizer.panelRadius': '6px',
        'playback.equalizer.sliderFill': 'linear-gradient(to top, #c2410c, #ea580c)',
        'playback.equalizer.spectrum': '#c2410c',
        'playback.equalizer.guide': 'rgba(194, 65, 12, 0.5)'
      },
      dark: {
        'color.primary.500': '#3ddc97',
        'color.primary.400': '#6fe7b2',
        'color.primary.300': '#a9f0cf',
        'color.primary.rgb': '61, 220, 151',
        'color.favorite': '#f87171',
        'color.warning': '#fbbf24',
        'color.neutral.200': '#262b2d',
        'color.neutral.300': '#3a4144',
        'color.neutral.500': '#8b9591',
        'color.neutral.700': '#c3cbc7',
        'color.neutral.900': '#e8ecea',
        'surface.app': '#121415',
        'surface.local': '#121415',
        'surface.settings': '#121415',
        'surface.streaming': '#121415',
        'surface.player': '#121415',
        'surface.card': '#1a1d1f',
        'surface.cardBorder': '#2e3437',
        'surface.subtle': '#17191b',
        'surface.hover': '#1e2224',
        'surface.active': 'rgba(61, 220, 151, 0.12)',
        'material.glass': '#1a1d1f',
        'material.glassStrong': '#202527',
        'material.glassBorder': '#2e3437',
        'material.glassShadow': 'none',
        'material.cardBlur': '0px',
        'material.cardSaturation': '100%',
        'material.glowMain': 'transparent',
        'navigation.surface': '#0e1011',
        'navigation.border': '#2e3437',
        'navigation.shadow': 'none',
        'navigation.activeSurface': 'rgba(61, 220, 151, 0.12)',
        'navigation.activeText': '#3ddc97',
        'navigation.indicator': '#3ddc97',
        'typography.sans': "'JetBrains Mono', 'Cascadia Code', 'MiSans', Consolas, monospace",
        'typography.display': "'JetBrains Mono', 'Cascadia Code', 'MiSans', Consolas, monospace",
        'typography.titleWeight': '600',
        'typography.bodyWeight': '400',
        'typography.bodySize': '13px',
        'shape.globalRadius': '4px',
        'shape.cardRadius': '6px',
        'motion.enter': 'cubic-bezier(0.2, 0, 0.4, 1)',
        'motion.soft': 'linear',
        'library.table.shadow': 'none',
        'library.selection.indicator': '#3ddc97',
        'library.selection.radius': '2px',
        'library.coverRadius': '2px',
        'playback.accent': '#3ddc97',
        'playback.backdrop.filter': 'blur(72px) saturate(0.5) brightness(0.26)',
        'playback.backdrop.scrim':
          'linear-gradient(180deg, rgba(8, 10, 10, 0.84), rgba(8, 10, 10, 0.88))',
        'playback.cover.radius': '4px',
        'playback.control.radius': '4px',
        'playback.control.borderWidth': '1px',
        'playback.progress.fill': 'linear-gradient(90deg, #3ddc97, #3ddc97)',
        'playback.progress.height': '3px',
        'playback.progress.radius': '0px',
        'playback.equalizer.panelRadius': '6px',
        'playback.equalizer.sliderFill': 'linear-gradient(to top, #10b981, #3ddc97)',
        'playback.equalizer.spectrum': '#3ddc97',
        'playback.equalizer.guide': 'rgba(61, 220, 151, 0.55)'
      }
    },
    {
      appearance: {
        accentSource: 'fixed',
        backgroundTreatment: 'solid',
        contrastGuard: 'enforce',
        effectsMode: 'reduced'
      },
      navigation: { style: 'compact', iconScale: 'sm', logo: 'hide' },
      library: { density: 'compact', selection: 'stroke', titleOverlay: 'off' },
      player: { layout: 'split', controls: 'pro', titleAlign: 'left', progress: 'line' },
      artwork: { transition: 'none', shadow: 'off' },
      equalizer: {
        panel: 'neutral',
        slider: 'solid',
        knob: 'line',
        spectrum: 'line',
        button: 'outline'
      },
      icons: { family: 'outline' },
      typography: { titleCase: 'uppercase', lyricAccent: 'accent', titleColor: 'off' },
      visibility: { ...allThemeVisibilitySlots, miniPlayerArtwork: false }
    },
    {
      miniPlayer: {
        surfaceColor: '#0e1011',
        accentColor: '#3ddc97',
        primaryTextColor: '#e8ecea',
        mutedTextColor: '#8b9591',
        fontFamily: "'JetBrains Mono', 'Cascadia Code', 'MiSans', Consolas, monospace",
        surfaceOpacity: 100,
        glassBlur: 0,
        cornerRadius: 6,
        borderWidth: 1,
        borderColor: '#2e3437',
        shadowStrength: 24,
        shadowColor: '#000000'
      },
      desktopLyrics: {
        fontFamily: "'JetBrains Mono', 'Cascadia Code', 'MiSans', Consolas, monospace",
        fontSize: 26,
        fontWeight: 500,
        color: '#c3cbc7',
        highlightColor: '#3ddc97',
        backgroundColor: '#0e1011',
        backgroundOpacity: 78,
        shadow: false,
        shadowBlur: 0,
        shadowColor: '#000000'
      }
    }
  ),
  builtInThemePreset(
    'builtin:zen-minimal',
    'Zen Minimal',
    '墨色与留白之间一抹苔绿静落，如茶室般仅以间距与浓淡安放层级。',
    {
      pureWhite: {
        'color.primary.500': '#47614f',
        'color.primary.400': '#5b7663',
        'color.primary.300': '#9db1a3',
        'color.primary.rgb': '71, 97, 79',
        'color.neutral.100': '#f1efe9',
        'color.neutral.200': '#e7e4da',
        'color.neutral.500': '#6b6e66',
        'color.neutral.700': '#3d403c',
        'color.neutral.900': '#26282a',
        'surface.app': '#f6f5f0',
        'surface.local': '#f6f5f0',
        'surface.settings': '#f6f5f0',
        'surface.streaming': '#f6f5f0',
        'surface.player': '#f6f5f0',
        'surface.card': '#fbfaf6',
        'surface.cardBorder': '#e7e4da',
        'surface.subtle': '#f1efe9',
        'surface.hover': '#edebe3',
        'surface.active': 'rgba(71, 97, 79, 0.1)',
        'material.glass': '#f6f5f0',
        'material.glassBorder': '#e7e4da',
        'material.glassShadow': 'none',
        'material.glowMain': 'transparent',
        'material.cardBlur': '0px',
        'material.cardSaturation': '100%',
        'shell.control.text': '#26282a',
        'shell.control.hoverSurface': 'rgba(38, 40, 42, 0.05)',
        'navigation.surface': '#f6f5f0',
        'navigation.border': 'transparent',
        'navigation.shadow': 'none',
        'navigation.text': '#595c55',
        'navigation.hoverSurface': 'rgba(38, 40, 42, 0.04)',
        'navigation.activeSurface': 'rgba(71, 97, 79, 0.09)',
        'navigation.activeText': '#47614f',
        'navigation.indicator': '#47614f',
        'typography.titleWeight': '500',
        'typography.bodyWeight': '400',
        'typography.chromeText': '#595c55',
        'shape.globalRadius': '10px',
        'shape.cardRadius': '12px',
        'library.page.surface': 'linear-gradient(180deg, #f6f5f0, #f6f5f0)',
        'library.row.text': '#3d403c',
        'library.row.hoverSurface': 'rgba(38, 40, 42, 0.035)',
        'library.selection.surface': 'rgba(71, 97, 79, 0.08)',
        'library.selection.indicator': '#47614f',
        'library.coverRadius': '8px',
        'playback.backdrop.filter': 'blur(72px) saturate(0.2) brightness(0.42)',
        'playback.backdrop.scrim':
          'linear-gradient(180deg, rgba(24, 26, 27, 0.62) 0%, rgba(24, 26, 27, 0.68) 50%, rgba(24, 26, 27, 0.76) 100%)',
        'playback.cover.radius': '12px',
        'playback.cover.shadow': 'none',
        'playback.control.radius': '10px',
        'playback.progress.track': 'rgba(255, 255, 255, 0.18)',
        'playback.progress.fill': 'linear-gradient(90deg, #b6c6ba, #b6c6ba)',
        'playback.progress.height': '2px',
        'playback.equalizer.panelSurface': '#fbfaf6',
        'playback.equalizer.panelBorder': '#e7e4da',
        'playback.equalizer.sliderTrack': 'rgba(38, 40, 42, 0.08)',
        'playback.equalizer.sliderFill': 'linear-gradient(to top, #47614f, #47614f)',
        'motion.enter': 'cubic-bezier(0.32, 0, 0.16, 1)',
        'motion.soft': 'cubic-bezier(0.45, 0.05, 0.15, 1)'
      },
      dark: {
        'color.primary.500': '#9eb5a4',
        'color.primary.400': '#b3c7ba',
        'color.primary.300': '#c9d7cd',
        'color.primary.rgb': '158, 181, 164',
        'color.neutral.100': '#1b1d1f',
        'color.neutral.200': '#292c2e',
        'color.neutral.500': '#9a9d97',
        'color.neutral.700': '#c8c8c0',
        'color.neutral.900': '#e9e7df',
        'surface.app': '#17191b',
        'surface.local': '#17191b',
        'surface.settings': '#17191b',
        'surface.streaming': '#17191b',
        'surface.player': '#17191b',
        'surface.card': '#1d2022',
        'surface.cardBorder': '#2c2f31',
        'surface.subtle': '#1a1d1f',
        'surface.hover': 'rgba(255, 255, 255, 0.045)',
        'surface.active': 'rgba(158, 181, 164, 0.12)',
        'material.glass': '#17191b',
        'material.glassBorder': '#2c2f31',
        'material.glassShadow': 'none',
        'material.glowMain': 'transparent',
        'material.cardBlur': '0px',
        'material.cardSaturation': '100%',
        'shell.control.text': '#e9e7df',
        'shell.control.hoverSurface': 'rgba(255, 255, 255, 0.05)',
        'navigation.surface': '#17191b',
        'navigation.border': 'transparent',
        'navigation.shadow': 'none',
        'navigation.text': '#b6b9b1',
        'navigation.hoverSurface': 'rgba(255, 255, 255, 0.04)',
        'navigation.activeSurface': 'rgba(158, 181, 164, 0.1)',
        'navigation.activeText': '#9eb5a4',
        'navigation.indicator': '#9eb5a4',
        'typography.titleWeight': '500',
        'typography.bodyWeight': '400',
        'typography.chromeText': '#b6b9b1',
        'shape.globalRadius': '10px',
        'shape.cardRadius': '12px',
        'library.page.surface': 'linear-gradient(180deg, #17191b, #17191b)',
        'library.row.text': '#c8c8c0',
        'library.row.hoverSurface': 'rgba(255, 255, 255, 0.04)',
        'library.selection.surface': 'rgba(158, 181, 164, 0.1)',
        'library.selection.indicator': '#9eb5a4',
        'library.coverRadius': '8px',
        'playback.backdrop.filter': 'blur(72px) saturate(0.2) brightness(0.3)',
        'playback.backdrop.scrim':
          'linear-gradient(180deg, rgba(24, 26, 27, 0.62) 0%, rgba(24, 26, 27, 0.68) 50%, rgba(24, 26, 27, 0.76) 100%)',
        'playback.cover.radius': '12px',
        'playback.cover.shadow': 'none',
        'playback.control.radius': '10px',
        'playback.progress.track': 'rgba(255, 255, 255, 0.14)',
        'playback.progress.fill': 'linear-gradient(90deg, #9eb5a4, #9eb5a4)',
        'playback.progress.height': '2px',
        'playback.equalizer.panelSurface': '#1d2022',
        'playback.equalizer.panelBorder': '#2c2f31',
        'playback.equalizer.sliderTrack': 'rgba(255, 255, 255, 0.09)',
        'playback.equalizer.sliderFill': 'linear-gradient(to top, #9eb5a4, #9eb5a4)',
        'motion.enter': 'cubic-bezier(0.32, 0, 0.16, 1)',
        'motion.soft': 'cubic-bezier(0.45, 0.05, 0.15, 1)'
      }
    },
    {
      appearance: {
        accentSource: 'fixed',
        backgroundTreatment: 'solid',
        contrastGuard: 'enforce',
        effectsMode: 'reduced'
      },
      navigation: { style: 'rail', iconScale: 'sm', logo: 'hide' },
      library: { density: 'comfortable', selection: 'stroke', titleOverlay: 'off' },
      player: { layout: 'minimal', controls: 'standard', titleAlign: 'center', progress: 'line' },
      artwork: { transition: 'fade', shadow: 'off' },
      equalizer: {
        panel: 'neutral',
        slider: 'solid',
        knob: 'dot',
        spectrum: 'line',
        button: 'outline'
      },
      icons: { family: 'outline' },
      typography: { titleCase: 'preserve', lyricAccent: 'off', titleColor: 'off' },
      visibility: {
        ...allThemeVisibilitySlots,
        playerAlbumArtist: false,
        playerTrackMenu: false,
        playerMiscIcons: false,
        playerDuration: false,
        playerWaveform: false,
        equalizerGrid: false,
        equalizerFrequencyGuides: false,
        equalizerSpectrum: false,
        miniPlayerArtwork: false
      }
    },
    {
      miniPlayer: {
        surfaceColor: '#f6f5f0',
        accentColor: '#47614f',
        primaryTextColor: '#26282a',
        mutedTextColor: '#6b6e66',
        fontFamily: lightFont,
        surfaceOpacity: 98,
        glassBlur: 0,
        cornerRadius: 12,
        borderWidth: 1,
        borderColor: '#e0ddd3',
        shadowStrength: 0,
        shadowColor: '#000000'
      },
      desktopLyrics: {
        fontFamily: lightFont,
        fontSize: 30,
        fontWeight: 400,
        color: '#e9e7df',
        highlightColor: '#b3c7ba',
        backgroundColor: '#17191b',
        backgroundOpacity: 62,
        shadow: false,
        shadowBlur: 0,
        shadowColor: '#000000'
      }
    }
  )
])
const builtInThemePresetById = new Map(
  BUILT_IN_THEME_PRESETS.map((preset) => [preset.id as BuiltInThemePresetId, preset])
)

export function isBuiltInThemePresetId(value: unknown): value is BuiltInThemePresetId {
  return typeof value === 'string' && builtInThemePresetById.has(value as BuiltInThemePresetId)
}

export function getBuiltInThemePreset(value: unknown): ThemeProfileV2 | null {
  return isBuiltInThemePresetId(value) ? (builtInThemePresetById.get(value) ?? null) : null
}
